apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  labels:
    app: nginx
    env: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      env: blue
  template:
    metadata:
      labels:
        app: nginx
        env: blue
    spec:
      containers:
        - name: nxctr
          image: nginx:bluegreen
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.2"
            limits:
              memory: "64Mi"
              cpu: "0.25"
