apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgdeploy-blue
  labels:
    app: bgdeploy
    env: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bgdeploy
      env: blue
  template:
    metadata:
      labels:
        app: bgdeploy
        env: blue
    spec:
      containers:
        - name: bgd-ctr
          image: bgdeploy:1.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.2"
            limits:
              memory: "64Mi"
              cpu: "0.25"
