apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 8080 # svc port
    targetPort: 80 # container port
    nodePort: 32123 # node port
    protocol: TCP
  type: NodePort