apiVersion: v1
kind: Service
metadata:
  name: bgd-svc
spec:
  selector:
    app: bgdeploy
    env: blue # change colour to point to the stand-by environment
  ports:
    - name: http
      port: 8080 # svc port
      targetPort: 80 # ep port
      nodePort: 32123 # node port
      protocol: TCP
  type: NodePort
