apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgdeploy-green
  labels:
    app: bgdeploy
    env: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bgdeploy
      env: green
  template:
    metadata:
      labels:
        app: bgdeploy
        env: green
    spec:
      containers:
        - name: bgd-ctr
          image: bgdeploy:2.0 # update image to the new app version
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.2"
            limits:
              memory: "64Mi"
              cpu: "0.25"
