apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  labels:
    app: nginx
    env: green
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
      env: green
  template:
    metadata:
      labels:
        app: nginx
        env: green
    spec:
      containers:
        - name: nxctr
          image: nginx:bluegreen
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.2"
            limits:
              memory: "64Mi"
              cpu: "0.25"
